server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.5.152:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'