server:
  port: 8401
spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.5.152:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
#        dashboard: 47.100.5.152:9001 #配置Sentinel dashboard地址
        #client-ip: 8ca65248d673.ngrok.io
      datasource:
        ds1:
          nacos:
            server-addr: 47.100.5.152:8848
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            data-type: json #数据格式
            # 规则类型，取值见：
            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
            rule-type: flow



management:
  endpoints:
    web:
      exposure:
        include: '*'

#单独例子