server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
        loggerLevel: full

logging:
  level:
    com.wt.springcloud.service.PaymentHystrixService: debug